### ISSUE TITLE
type 'int' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by stwonary** [dengyin2000/dynamic_widget#50]
When minifying a JSON. any `double` without decimal are converted into `int` type

Original
```
    {
      "type": "SizedBox",
      "height": 19.0,
      "child": {
        "type": "Container",
        "color": "#FFFFFF"
      }
    },
```

minified 
```
{"type":"SizedBox","height":19,"child":{"type":"Container","color":"#FFFFFF"}}
```

https://codebeautify.org/jsonminifier

Error when building above JSON
```
The following _TypeError was thrown building BlocBuilder<Cubit, String>
type 'int' is not a subtype of type 'double'

The relevant error-causing widget was: 
  BlocBuilder<Cubit, String>home_page.dart:
When the exception was thrown, this was the stack: 
#0      SizedBoxWidgetParser.parse (package:dynamic_widget/dynamic_widget/basic/sizedbox_widget_parser.dart:34:18)
#1      DynamicWidgetBuilder.buildFromMap (package:dynamic_widget/dynamic_widget.dart:116:21)
#2      DynamicWidgetBuilder.buildWidgets (package:dynamic_widget/dynamic_widget.dart:127:14)
#3      ListViewWidgetParser.parse (package:dynamic_widget/dynamic_widget/scrolling/listview_widget_parser.dart:27:41)
#4      DynamicWidgetBuilder.buildFromMap (package:dynamic_widget/dynamic_widget.dart:116:21)
```

There is a PR #48  which solve this issue on some Parser. Still missing the fix in `SizedBox` parser though.

**Comment by dengyin2000** [comment]
I think it's the jsonminifier tool's bug, and thanks for your PR.

**Comment by stwonary** [comment]
Not my PR, but thank you for merging it! 

Actually, in JSON there is no `int` nor `double` datatype, but just a `number` datatype

![json](https://www.json.org/img/number.png)
